logging:
  level: INFO
  loggers:
    com.motivity: DEBUG


database :
 driverClass: com.mysql.cj.jdbc.Driver
 url: jdbc:mysql://localhost:3306/lotus?autoReconnect=true&useSSL=false
 user: root
 password: root