logging:
  level: INFO
  loggers:
    com.motivity: DEBUG
    aditive: true
  
  appenders:
    - type: console
      timeZone: IST
      logFormat: "%-5p [%d{ISO8601,IST}] %c: %m%n%rEx"
    
    - type: file
      currentLogFilename: D:\DropWizard\DropwizardLogging\dwl.log
      timeZone: IST
      logFormat: "%-5p [%d{ISO8601,IST}] %c: %m%n%rEx"
      archive: true
      archivedLogFilenamePattern: F:\Dropwizard\dropwizardlogging\dwl-%d.log
      archivedFileCount: 5